version: '3.8'

services:
  django:
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - ./backend:/app
  frontend:
    command: npm run build
    volumes:
      - ./frontend:/app
