# Generated by Codex on 2026-05-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_otp_alter_customuser_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("university", models.CharField(max_length=255)),
                ("qualification", models.CharField(max_length=100)),
                ("address", models.TextField()),
                (
                    "id_front",
                    models.ImageField(blank=True, null=True, upload_to="tutors/cccd/"),
                ),
                (
                    "id_back",
                    models.ImageField(blank=True, null=True, upload_to="tutors/cccd/"),
                ),
                (
                    "degree_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="tutors/degrees/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Dang cho duyet"),
                            ("APPROVED", "Da duyet"),
                            ("REJECTED", "Da tu choi"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TutorAchievement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="tutors/achievements/")),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="users.tutorprofile",
                    ),
                ),
            ],
        ),
    ]
