# Generated by Django 5.0.14 on 2026-05-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_tutorprofile_tutorachievement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Đang chờ duyệt"),
                    ("APPROVED", "Đã duyệt"),
                    ("REJECTED", "Đã từ chối"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
