# Generated by Django 5.0.14 on 2026-05-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_feedback_moderation_and_tutor_student_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Đang học"),
                    ("completed", "Hoàn thành"),
                    ("paused", "Tạm dừng"),
                    ("cancelled", "Đã hủy"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sessionmaterial",
            name="material_type",
            field=models.CharField(
                choices=[
                    ("note", "Ghi chú"),
                    ("image", "Hình ảnh"),
                    ("file", "File tài liệu"),
                    ("video", "Video"),
                    ("link", "Đường dẫn"),
                ],
                default="note",
                max_length=20,
            ),
        ),
    ]
