from django.urls import path
from .views import (
    StudentCourseListView,
    StudentCourseDetailView,
    StudentSessionCompleteView,
    SessionMaterialDownloadView,
    StudentCourseReviewView,
    StudentCourseExtensionRequestView,
    StudentCourseCancellationRequestView,
    TutorCourseListView,
    TutorCourseDetailView,
    TutorCourseReviewListView,
    TutorStudentFeedbackCreateView,
    TutorStudentFeedbackListView,
    TutorExtensionRequestListView,
    TutorExtensionRequestDecisionView,
    TutorCourseCancellationRequestView,
    TutorSessionUpdateView,
    TutorSessionMaterialUploadView,
    TutorSessionMaterialPresignView,
    TutorSessionMaterialCompleteView,
    TutorStudyRoomListCreateView,
    TutorStudyRoomDetailView,
    TutorStudyRoomStudentsView,
    TutorStudyRoomSessionCreateView,
    TutorStudyRoomSessionDetailView,
    TutorStudyRoomMaterialView,
    TutorStudyRoomMaterialPresignView,
    TutorStudyRoomMaterialCompleteView,
    StudentStudyRoomListView,
    StudentStudyRoomDetailView,
    StudentStudyRoomSessionReadView,
)

urlpatterns = [
    # Student endpoints
    path("student/", StudentCourseListView.as_view(), name="student-courses"),
    path(
        "student/<int:pk>/",
        StudentCourseDetailView.as_view(),
        name="student-course-detail",
    ),
    path(
        "student/<int:pk>/review/",
        StudentCourseReviewView.as_view(),
        name="student-course-review",
    ),
    path(
        "student/<int:pk>/extend/",
        StudentCourseExtensionRequestView.as_view(),
        name="student-course-extend",
    ),
    path(
        "student/<int:pk>/cancel/",
        StudentCourseCancellationRequestView.as_view(),
        name="student-course-cancel",
    ),
    path(
        "sessions/<int:session_id>/complete/",
        StudentSessionCompleteView.as_view(),
        name="session-complete",
    ),
    path(
        "materials/<int:material_id>/download/",
        SessionMaterialDownloadView.as_view(),
        name="session-material-download",
    ),
    # Tutor endpoints
    path("tutor/", TutorCourseListView.as_view(), name="tutor-courses"),
    path(
        "tutor/reviews/",
        TutorCourseReviewListView.as_view(),
        name="tutor-course-reviews",
    ),
    path(
        "tutor/extensions/",
        TutorExtensionRequestListView.as_view(),
        name="tutor-extension-requests",
    ),
    path(
        "tutor/extensions/<int:pk>/decision/",
        TutorExtensionRequestDecisionView.as_view(),
        name="tutor-extension-decision",
    ),
    path(
        "tutor/<int:pk>/", TutorCourseDetailView.as_view(), name="tutor-course-detail"
    ),
    path(
        "tutor/<int:pk>/cancel/",
        TutorCourseCancellationRequestView.as_view(),
        name="tutor-course-cancel",
    ),
    path(
        "tutor/<int:pk>/student-feedback/",
        TutorStudentFeedbackCreateView.as_view(),
        name="tutor-student-feedback-create",
    ),
    path(
        "tutor/students/<int:student_id>/feedbacks/",
        TutorStudentFeedbackListView.as_view(),
        name="tutor-student-feedback-list",
    ),
    path(
        "tutor/sessions/<int:session_id>/update/",
        TutorSessionUpdateView.as_view(),
        name="tutor-session-update",
    ),
    path(
        "tutor/sessions/<int:session_id>/materials/",
        TutorSessionMaterialUploadView.as_view(),
        name="tutor-session-materials",
    ),
    path(
        "tutor/sessions/<int:session_id>/materials/presign/",
        TutorSessionMaterialPresignView.as_view(),
        name="tutor-session-material-presign",
    ),
    path(
        "tutor/materials/<int:material_id>/complete/",
        TutorSessionMaterialCompleteView.as_view(),
        name="tutor-session-material-complete",
    ),
    # Study rooms
    path(
        "rooms/tutor/", TutorStudyRoomListCreateView.as_view(), name="tutor-study-rooms"
    ),
    path(
        "rooms/tutor/<int:pk>/",
        TutorStudyRoomDetailView.as_view(),
        name="tutor-study-room-detail",
    ),
    path(
        "rooms/tutor/<int:pk>/students/",
        TutorStudyRoomStudentsView.as_view(),
        name="tutor-study-room-students",
    ),
    path(
        "rooms/tutor/<int:pk>/sessions/",
        TutorStudyRoomSessionCreateView.as_view(),
        name="tutor-study-room-sessions",
    ),
    path(
        "rooms/tutor/sessions/<int:session_id>/",
        TutorStudyRoomSessionDetailView.as_view(),
        name="tutor-study-room-session-detail",
    ),
    path(
        "rooms/tutor/sessions/<int:session_id>/materials/",
        TutorStudyRoomMaterialView.as_view(),
        name="tutor-study-room-materials",
    ),
    path(
        "rooms/tutor/sessions/<int:session_id>/materials/presign/",
        TutorStudyRoomMaterialPresignView.as_view(),
        name="tutor-study-room-material-presign",
    ),
    path(
        "rooms/tutor/materials/<int:material_id>/complete/",
        TutorStudyRoomMaterialCompleteView.as_view(),
        name="tutor-study-room-material-complete",
    ),
    path(
        "rooms/student/", StudentStudyRoomListView.as_view(), name="student-study-rooms"
    ),
    path(
        "rooms/student/<int:pk>/",
        StudentStudyRoomDetailView.as_view(),
        name="student-study-room-detail",
    ),
    path(
        "rooms/student/sessions/<int:session_id>/read/",
        StudentStudyRoomSessionReadView.as_view(),
        name="student-study-room-session-read",
    ),
]
